### ISSUE TITLE
Treetop Treasures Flash and CPI versions should be considered separate tracks

### ISSUE THREAD

**Issue by Hackinator20** [nhaar/CPOSTList#2]
The CPI version seems to be a different version than the Flash version (akin to Flash's This is CPSN vs CPI's CPSN). You can tell the flute is different, and there's a new section at the end of the CPI version (at about the 1:41 mark) not present in any of the Flash/Classic versions that contains some CPI-related motifs.

Flash: https://soundcloud.com/clubpenguin/treetop-treasures

CPI: https://soundcloud.com/user-764833925/treetop-treasures

**Comment by nhaar** [comment]
I believe I've covered this, let me know if I should do anything else

**Comment by Hackinator20** [comment]
You forgot to change the source for Flash Treetop Treasures from CPI Soundcloud to the original CP Soundcloud
